import { GeistSans, GeistMono } from 'next/font/google';
import './globals.css';

// Define fonts
const geistSans = GeistSans({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = GeistMono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// Metadata export
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// RootLayout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
